### ISSUE TITLE
www concat bug

### ISSUE THREAD

**Issue by chancesmith** [sodiumhalogenteam/litmus-lab#15]
Tried to do a build, but found this test failed before pushing up:
![](https://sh-drop.s3.us-east-1.amazonaws.com/cs/Screenshot%202018-12-13%2015.03.00.png)

Any good ideas on a workaround?

**Comment by adamcurl** [comment]
My first idea is to look at the url and see if 'http' is at the front of it. If so, then after the first '://', add 'www.'

**Comment by chancesmith** [comment]
What about that first pass? ^^^

**Comment by adamcurl** [comment]
seems to be working for me
