### ISSUE TITLE
check for JQuery version

### ISSUE THREAD

**Issue by chancesmith** [sodiumhalogenteam/litmus-lab#16]
> The report concludes that unless you are using jQuery 3.4.0 and above then you are using vulnerable jQuery versions.
- https://it.slashdot.org/story/19/11/10/001229/6-in-10-websites-may-be-impacted-by-jquery-xss-vulnerabilities?utm_source=rss1.0mainlinkanon&utm_medium=feed

Check Jquery, but not with the alert. 😝 
```
if (typeof jQuery != 'undefined') {
  // jQuery is loaded => print the version
  alert(jQuery.fn.jquery);
}
```

**Comment by jamespeach02** [comment]
I've pushed a feature that checks the jQuery version and tells you if the version is safe or not into the james-branch branch.
