### ISSUE TITLE
need to ignore img src data:image

### ISSUE THREAD

**Issue by chancesmith** [sodiumhalogenteam/litmus-lab#21]
`✕ http://www.sodiumhalogen.com/data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wgARCAAUABQDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQFAQL/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAHR8S8KkgzpAsB//8QAHRAAAQQCAwAAAAAAAAAAAAAAAQACAxESIQQTQf/aAAgBAQABBQJ8loSYrvcs9F7aB1yNS+B5r//EABQRAQAAAAAAAAAAAAAAAAAAACD/2gAIAQMBAT8BH//EABQRAQAAAAAAAAAAAAAAAAAAACD/2gAIAQIBAT8BH//EABoQAAMAAwEAAAAAAAAAAAAAAAABETFBUWH/2gAIAQEABj8Cg+mitxHWYJ4IR//EABwQAQEAAgMBAQAAAAAAAAAAAAEAESExUWFBkf/aAAgBAQABPyHDRobKIJ7h/n4jAeAZ5BE4CfojocEdR2LV/9oADAMBAAIAAwAAABCDBwD/xAAUEQEAAAAAAAAAAAAAAAAAAAAg/9oACAEDAQE/EB//xAAUEQEAAAAAAAAAAAAAAAAAAAAg/9oACAECAQE/EB//xAAcEAEAAgIDAQAAAAAAAAAAAAABABEhMVFxoWH/2gAIAQEAAT8QbGVWdsOhZRSh+nMCwdY2b9ihlrahnqNDLRvyENpbRIDWgUFXd8xNDG3HcDeiSq3P/9k= leads to a 404`

**Comment by jamespeach02** [comment]
I fixed this issue. The tool should no longer count images as 404s. My bug fix is in the branch called "james-branch"
