### ISSUE TITLE
streamline notifications

### ISSUE THREAD

**Issue by SZBoatwright** [sodiumhalogenteam/litmus-lab#23]
![Screen Shot 2019-11-18 at 2 35 04 PM](https://user-images.githubusercontent.com/32583478/69091807-aad40e80-0a10-11ea-850b-4013abb41a5b.png)

A lot of the wording when being notified of the different checks seems redundant, and takes up more space than it needs to.  Here are some specific examples: 

- Most of the notifications mention the url being tested. I would think the only time any URLs should be listed is when it's a broken link. It's confusing otherwise and adds visual clutter
- Since there is already a `✅/❌` next to each test, saying in the text that it did/didn't fail seems unnecessary. Instead, it would be more clear to just have the title of the test. So, when checking for a sitemap, instead of `❌ a sitemap does not exist for tcalions.com` or `✅ a sitemap does exist for tcalions.com`  just put either `❌ sitemap exists` or `✅ sitemap exists` so that there's less text. The emoji lets the user know that the test did/didn't fail, so having the text say as well just adds more visual clutter.

**Comment by jamespeach02** [comment]
I think I streamlined the notifications. Check out what I did and let me know what you think.
