### ISSUE TITLE
Add in command prompt/flag option to only show errors

### ISSUE THREAD

**Issue by adamcurl** [sodiumhalogenteam/litmus-lab#26]
We need to have an option to ask users if they would like to see all output or just errors. 

We need:
1. Flag option `npx litmus-lab -s sodiumhalogen.com -f` (the `f` flag is for "filtered" view)
2. A command prompt option to ask the user if they would like to only see errors

**Comment by jamespeach02** [comment]
This feature has been added in the james-branch.
