### ISSUE TITLE
add version tag

### ISSUE THREAD

**Issue by chancesmith** [sodiumhalogenteam/litmus-lab#7]
```
var pjson = require("./package.json");
pjson.version
```

I've used [commander](https://www.npmjs.com/package/commander) for CLI args (instead of yargs-paser):
```javascript
const program = require("commander");
var pjson = require("./package.json");

program
  .version(pjson.version)
  .option("-s, --site", "website")
```

[Commander](https://www.npmjs.com/package/commander) might also help solve the [Webpack packing issue](https://github.com/sodiumhalogenteam/litmus-lab/pull/1) I ran into last week.

Then $`litmus-lab --verison` is available to show the user the version.

**Comment by adamcurl** [comment]
Added version tag. However, running the command for the checkVersion() function doesn't quite work.

**Comment by chancesmith** [comment]
Nah, what you have is great. Just using the tool shows if there is an update you can fetch. All good here, man!

**Comment by chancesmith** [comment]
Adam's commit f569d9647aa70bd9a926546d5e6fa48005e287b6 did the trick.
