### ISSUE TITLE
google analtyics checker doesn't show "not found" log

### ISSUE THREAD

**Issue by chancesmith** [sodiumhalogenteam/litmus-lab#8]
I tested `adamcurl.com` and don't see analytics found or not.

![](https://sh-drop.s3.us-east-1.amazonaws.com/cs/litmus-analytics-issue-2018-12-03%2006.42.23.png)

I checked for Google Analytics on `chancesmith.org`:
No analytics found there. I have [analtyics script added](http://www.chancesmith.org/). 😕

**Comment by chancesmith** [comment]
Surfacing this for one more bug. 

ChanceSmith.org has Google Analytics but the Litmus-Lab doesn't find it:
![](https://www.dropbox.com/s/sf8gd8mh6h11f6u/Screenshot%202018-12-03%2014.00.09.png?dl=0)

**Comment by adamcurl** [comment]
Fixed in master branch for sure this time!
